name: Desligar VM

on:
  workflow_dispatch:

jobs:
  desligar-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar no GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Desligar VM
        run: |
          gcloud compute instances stop ${{ secrets.VM_NAME}} \
            --zone="${{ secrets.ZONE }}" \
            --project="${{ secrets.GCP_PROJECT_ID }}"