name: Ligar VM

on:
  schedule:
    - cron: '50 11 * * 5'
jobs:
  ligar-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar no GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Ligar a VM
        run: |
          gcloud compute instances start ${{ secrets.VM_NAME}} \
            --zone="${{ secrets.ZONE }}" \
            --project="${{ secrets.GCP_PROJECT_ID }}"