name: Ligar e Desligar VM

on:
  workflow_dispatch:

jobs:
  ligar-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar no GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}



